[package]
name = "InterpretedLanguage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
chumsky = "0.9.2"
ariadne = "0.3.0"

